#!/usr/bin/env ruby

require "thor"
require "uri"
require "rest-client"

require_relative "validator_lib"

class ValidatorCLI < Thor
  include ValidatorLib

  def self.exit_on_failure?
	  true
	end

  class_option :host,
    :desc => %Q(
      When following links, replaces the link's host with the given host.

      When this option is set, will also replace all 'https' schemes with 'http'.

      This option is useful for local development. E.g. when serving from a local server on port 3000,
      pass --host="localhost:3000" to make the validator follow links on the local machine.
    ), :default => nil, :type => :string

  desc "all MANIFEST_FILE_OR_URL", "Validates scheduling links MANIFEST_FILE_OR_URL."
  long_desc <<-DESC
    Validates the specified manifest file and all named resources.

    You may pass in a path or a URL to validate.
  DESC
  def all(file_or_url)
    puts "Validating #{file_or_url} and all referenced resources"
    state = State.new
    errors = validate_manifest_helper(state, file_or_url)

    resources = manifest_resources(read_resource(file_or_url))
    resources.each_with_index do |res, idx|
      puts "Validating [%5d/%5d]: #{res[:type]} file #{res[:url]}" % [idx+1, resources.length]
      case res[:type]
      when "Location"
        errors.concat validate_location(state, res[:url], read_resource(res[:url]))
      when "Schedule"
        errors.concat validate_schedule(state, res[:url], read_resource(res[:url]))
      when "Slot"
        errors.concat validate_slot(state, res[:url], read_resource(res[:url]))
      else
        raise Thor::Error, "Unknown manifest resource type #{res[:type]}"
      end
    end
    print_errors(errors)
  end

  desc "manifest MANIFEST_FILE_OR_URL", "Validates manifest MANIFEST_FILE_OR_URL."
  long_desc <<-DESC
    Validates the specified manifest file.

    You may pass in a path or a URL to validate.

    Note that this option validates only the manifest file - resources named by the manifest
    file are not validated. To validate all named resources, use the 'all' command.
  DESC
  def manifest(file_or_url)
    puts "Validating manifest #{file_or_url}"

    state = State.new
    print_errors(validate_manifest_helper(state, file_or_url))
  end

  desc "location LOCATION_FILE_OR_URL", "Validates location LOCATION_FILE_OR_URL."
  def location(file_or_url)
    puts "Validating location #{file_or_url}"
    errors = []
    state = State.new
    errors.concat(validate_location(state, file_or_url, read_resource(file_or_url)))
    errors.concat(state.errors())
  end

  desc "schedule SCHEDULE_FILE_OR_URL", "Validates schedule SCHEDULE_FILE_OR_URL."
  def schedule(file_or_url)
    puts "Validating schedule #{file_or_url}"
    errors = []
    state = State.new
    errors.concat(validate_schedule(state, file_or_url, read_resource(file_or_url)))
    errors.concat(state.errors())
  end

  desc "slot SLOT_FILE_OR_URL", "Validates location SLOT_FILE_OR_URL."
  def slot(file_or_url)
    puts "Validating slot #{file_or_url}"
    errors = []
    state = State.new
    errors.concat(validate_slot(state, file_or_url, read_resource(file_or_url)))
    errors.concat(state.errors())
  end

 private

 # Validates the given manifest file or URL. Returns an array of errors.
  def validate_manifest_helper(state, f)
    errors = []
    errors.concat(validate_manifest_url_path(f))

    errors.concat(validate_manifest(state, f, read_resource(f)))
    errors.concat(state.errors())
  end

  # If errors is not empty - prints the contents of errors and raises a Thor::Error.
  def print_errors(errors)
    unless errors.empty?
      say "Validation failed", Shell::Color::RED
      raise Thor::Error, "#{errors.join("\n")}"
    else
      say "Validation succeeded!", Shell::Color::GREEN
    end
  end

  # Attempts to get the contents of loc, which may be a URL or file path.
  # If the read fails, raises an error.
  # Returns a string containing the contents of the URL or file.
  def read_resource(loc)
    if is_url(loc)
      url = URI.parse(loc)
      resp_body = ""
      if options[:host] != nil
        uri.host, uri.port = options[:host].split(":")
        uri.scheme = "http"
      end

      resp = RestClient.get(url.to_s, headers: {"User-Agent" => "github.com/lazau/scheduling-links-aggregator/validator"})
      if resp.code != 200
        raise Thor::Error, "Unable to fetch #{loc}: HTTP response code #{resp.code}"
      end
      return resp.body
    end

    if !File.exist?(loc)
      raise Thor::Error, "File #{loc} does not exist."
    end
    return File.read(loc)
  end
end

ValidatorCLI.start(ARGV)
